### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by phaethon** [boundlessgeo/mgrs-tools#3]
I tried installing mgrs-tools by using `git clone http://github.com...` in my plugins directory. When I open 'Manage and install plugins' I see MGRS tools in red. And clicking on it I see:
```
This plugin is broken
invalid syntax
```
Using Ubuntu 15.04, QGIS 2.4 from standard Ubuntu package.

**Comment by dakcarto** [comment]
Hi @phaethon,

Hmm. Looks like the repo name needs changed, to support this type cloned install. Basically, the plugin manager does not like the '-' in the name. When distributed, the plugin directory is actually named `mgrstools`. Try renaming the cloned local parent directory to that name and restart QGIS.

**Comment by phaethon** [comment]
Yes, that helped.
